apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: agents-skill
  namespace: kagent
spec:
  description: Kubernetes Expert AI Agent.
  type: Declarative
  declarative:
    modelConfig: default-model-config
    systemMessage: |
      You are a Kubernetes expert. Help debug and operate the cluster.
    tools:
      - type: McpServer
        mcpServer:
          name: kagent-tool-server
          kind: RemoteMCPServer
          apiGroup: kagent.dev
        # instead of toolNames, use filters or leave empty to allow all tools
        # this lets the agent see all tools from kagent-tool-server
