apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: llama3-model-config
  namespace: kagent
spec:
  apiKeySecretKey: OPENAI_API_KEY
  apiKeySecret: kagent-openai
  model: cai_cybersecurity_agent_gguf_fixed
  provider: Ollama
  ollama:
    host: http://10.0.5.50:11435
