apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: llama3-model-config
  namespace: kagent
spec:
  apiKeySecretKey: OPENAI_API_KEY
  apiKeySecret: kagent-openai
  model: deepseek-chat
  provider: OpenAI
  openAI:
    baseUrl: https://api.deepseek.com/v1
