apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: default-model-config
  namespace: kagent
spec:
  provider: Gemini
  model: gemini-3-flash-preview
  apiKeySecret: kagent-gemini
  apiKeySecretKey: GOOGLE_API_KEY
  gemini: {}
