apiVersion: v1
data:
  OPENAI_API_KEY: c2stY2E4MTg0OTg3Y2IwNGNlOTlmNjhiYWI3MDBkYTA3MjE=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: kagent
    meta.helm.sh/release-namespace: kagent
  labels:
    app.kubernetes.io/instance: kagent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kagent
    app.kubernetes.io/part-of: kagent
    app.kubernetes.io/version: 0.7.13
    helm.sh/chart: kagent-0.7.13
  name: kagent-openai
  namespace: kagent
type: Opaque
